apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: doppler-poproom
  namespace: default
spec:
  tokenSecret:
    name: doppler-token-poproom
  project: poproom
  config: prd
  managedSecret:
    name: poproom-backend-secret
    namespace: default
    type: Opaque
