apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - doppler-secret.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml
  - image-updater.yaml

images:
  - name: jeanmichelbb/poproom-fe
    newTag: b2e3674690b2def3e2b5e3018c762380207fd1aa
    newName: jeanmichelbb/poproom-fe
  - name: jeanmichelbb/poproom-be
    newTag: b2e3674690b2def3e2b5e3018c762380207fd1aa
    newName: jeanmichelbb/poproom-be
