apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - doppler-secret.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml
  - image-updater.yaml

images:
  - name: jeanmichelbb/poproom-fe
    newTag: fd93117dc573d1dce81d9585311a1197b5ab770d
    newName: jeanmichelbb/poproom-fe
  - name: jeanmichelbb/poproom-be
    newTag: 89beb5752e2a68fe4e976d1bbfa57f7f630d3c23
    newName: jeanmichelbb/poproom-be
